version: '3.1'

services:
  joomla:
    image: joomla:3.9.4-php7.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: mfnroot
    volumes:
      -  /mnt/swarm-shared/mfn-joomla:/var/www/html
    networks:
      - joomla-net

  joomladb:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mfnroot
      MYSQL_DATABASE: joomla
    volumes:
      -  /mnt/swarm-shared/mfn-mysql:/var/lib/mysql
    networks:
      - joomla-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: joomladb
      MYSQL_ROOT_PASSWORD: mfnroot
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    networks:
      - joomla-net

networks:
  joomla-net:
