version: '3.1'

services:
  joomla:
    image: joomla:3.9.2-php7.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: mfnroot
    volumes:
      - ~/temp/mfn-joomla:/var/www/html
    networks:
      - joomla-net

  joomladb:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mfnroot
    volumes:
      - ~/temp/mfn-mysql:/var/lib/mysql
    networks:
      - joomla-net

networks:
  joomla-net:
